### PR TITLE
Optional System SQLite

### PR DESCRIPTION
**Pull request by oz123**
As discussed in #4 .

### CODE REVIEW

**Comment by andrewchambers** [comment]
I would consider prefixing the env var with JANET_  not too sure though.

**Comment by oz123** [comment]
@andrewchambers seems that this is convention to follow. I change the code as you suggested.

**Comment by bakpakin** [comment]
LGTM.

**Comment by oz123** [comment]
@bakpakin is there something else that should be done to get this merged?

**Pull request merged**
